Automação Web e Busca de Informações com Python
Desafio:
Trabalhamos em uma importadora e o preço dos nossos produtos é vinculado a cotação de:

Dólar
Euro
Ouro
Precisamos pegar na internet, de forma automática, a cotação desses 3 itens e saber quanto devemos cobrar pelos nossos produtos, considerando uma margem de contribuição que temos na nossa base de dados.

Base de Dados: https://drive.google.com/drive/folders/1o2lpxoi9heyQV1hIlsHXWSfDkBPtze-V?usp=sharing

Para isso, vamos criar uma automação web:

Usaremos o selenium
Importante: baixar o webdriver(é o driver do navegador)

PASSO 1: PEGAR A COTAÇÃO DO DOLAR
PASSO 2: PEGAR A COTAÇÃO DO EURO
PASSO 3:PEGAR A COTAÇÃO DO OURO
PASSO 4: IMPORTAR A LISTA DE PRODUTOS
PASSO 5: RECALCULAR O PREÇO DE CADA PRODUTO
PASSO 6: SALVAR OS NOVOS PREÇOS DOS PRODUTOS NO EXCEL

In [22]:
from selenium import webdriver
from selenium.webdriver.common.keys import Keys

# para rodar o chrome em 2º plano
# from selenium.webdriver.chrome.options import Options
# chrome_options = Options()
# chrome_options.headless = True # also works
# nav = webdriver.Chrome(options=chrome_options)

In [23]:
#ABRINDO NAVEGADOR

#PASSO 1: PEGAR A COTAÇÃO DO DOLAR
navegador = webdriver.Chrome()
#entrando em um site
navegador.get("https://www.google.com/")
#pegando o local que vc quer escrever ou manipular
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("Cotação dólar")
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
#pegando o valor de um atributo
cotacao_dolar = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")
print(cotacao_dolar)


#PASSO 2: PEGAR A COTAÇÃO DO EURO
navegador = webdriver.Chrome()
#entrando em um site
navegador.get("https://www.google.com/")
#pegando o local que vc quer escrever ou manipular
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys("Cotação euro")
navegador.find_element_by_xpath('/html/body/div[1]/div[3]/form/div[1]/div[1]/div[1]/div/div[2]/input').send_keys(Keys.ENTER)
#pegando o valor de um atributo
cotacao_euro = navegador.find_element_by_xpath('//*[@id="knowledge-currency__updatable-data-column"]/div[1]/div[2]/span[1]').get_attribute("data-value")
print(cotacao_euro)


#PASSO 3:PEGAR A COTAÇÃO DO OURO
    
navegador = webdriver.Chrome()
#entrando em um site
navegador.get("https://www.melhorcambio.com/ouro-hoje")
#pegando o valor de um atributo
cotacao_ouro = navegador.find_element_by_xpath('//*[@id="comercial"]').get_attribute("value")
cotacao_ouro = cotacao_ouro.replace(",",".")
print(cotacao_ouro)
navegador.quit()

4.9144
5.863493500000001
280.47

In [24]:
#PASSO 4: IMPORTAR A LISTA DE PRODUTOS
import pandas as pd

tabela = pd.read_excel("Produtos.xlsx")
display(tabela)

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Margem,Preço Final
0,Câmera Canon,999.99,Dólar,5,4999.95,1.40,6999.930
1,Carro Renault,4500.00,Euro,6,27000.00,2.00,54000.000
2,Notebook Dell,899.99,Dólar,5,4499.95,1.70,7649.915
3,IPhone,799.00,Dólar,5,3995.00,1.70,6791.500
4,Carro Fiat,3000.00,Euro,6,18000.00,1.90,34200.000
5,Celular Xiaomi,480.48,Dólar,5,2402.40,2.00,4804.800
6,Joia 20g,20.00,Ouro,350,7000.00,1.15,8050.000

In [25]:
#PASSO 5: RECALCULAR O PREÇO DE CADA PRODUTO
#atualizar a cotação
#Nas linhas onde moeda é igual a dólar
tabela.loc[tabela["Moeda"] == "Dólar","Cotação"] = float(cotacao_dolar)
#Nas linhas onde moeda é igual a Euro
tabela.loc[tabela["Moeda"] == "Euro","Cotação"] = float(cotacao_euro)
#Nas linhas onde moeda é igual a Ouro
tabela.loc[tabela["Moeda"] == "Ouro","Cotação"] = float(cotacao_ouro)
#atualizar o preço base reais (preço original * cotação)
tabela["Preço Base Reais"] = tabela["Preço Base Original"] * tabela["Cotação"]
#atualizar preço final(preço base reais * margem)
tabela["Preço Final"] = tabela["Preço Base Reais"] * tabela["Margem"]
display(tabela)

,Produtos,Preço Base Original,Moeda,Cotação,Preço Base Reais,Margem,Preço Final
0,Câmera Canon,999.99,Dólar,4.914400,4914.350856,1.40,6880.091198
1,Carro Renault,4500.00,Euro,5.863494,26385.720750,2.00,52771.441500
2,Notebook Dell,899.99,Dólar,4.914400,4422.910856,1.70,7518.948455
3,IPhone,799.00,Dólar,4.914400,3926.605600,1.70,6675.229520
4,Carro Fiat,3000.00,Euro,5.863494,17590.480500,1.90,33421.912950
5,Celular Xiaomi,480.48,Dólar,4.914400,2361.270912,2.00,4722.541824
6,Joia 20g,20.00,Ouro,280.470000,5609.400000,1.15,6450.810000

In [26]:
#PASSO 6: SALVAR OS NOVOS PREÇOS DOS PRODUTOS
tabela.to_excel("Produtos Novo.xlsx", index=False)